### PR TITLE
Fix/non-RESTful endpoints

### LINKED ISSUE #41: *BE* Fix count_items method to pass Postman test
Currently the Postman test for count_items is expecting 15 but getting 37. If we call `.distinct`, it changes to 9

### LINKED ISSUE #48: *BE* Fix non-RESTful endpoints and improve test coverage
As it stands, there are quite a few Postman tests failing and a couple RSpec tests failing, along with a lack of RSpec tests for both happy and sad paths for these endpoints

### PR DESCRIPTION
**Pull request by JarenGarman**
# Pull Request

## Type of change

- [ ] New feature
- [X] Bug Fix

## Check the correct boxes

- [X] This code broke nothing
- [ ] This code broke some stuff
- [ ] This code broke everything

## Implements/Fixes

- Fixes MVC violations by extracting complex AR requests to model class methods
- Improves error handling and testing relating to find and find_all endpoints
- Restores 100% test coverage for all of: models, requests, and entire suite
- Passes all Postman tests (except for the two broken ones which have been reported)
- Closes #41 
- Closes #48 

## Testing Changes

- [X] I have fully tested my code
- [X] All tests are passing
- [ ] Some tests are failing
- [ ] All tests are failing

- [ ] No previous tests have been changed
- [X] Some previous tests have been changed
- [ ] All of the previous tests have been changed (Please describe what in the world happened that all of the previous tests needed changing.)

## Checklist

- [X] I have reviewed my code
- [X] The code will run locally
- [X] My code has no unused/commented out code
- [ ] I have commented my code, particularly in hard-to-understand areas

## (For Fun!) Please include a link to a gif [or add an emoji] of your feelings about this branch

[Link](https://media.giphy.com/media/KB7Moe2Oj0BXeDjvDp/giphy.gif?cid=790b7611zhrrceti1jj5d4xsb54h3eb1b0bgkhaph5gni5qk&ep=v1_gifs_search&rid=giphy.gif&ct=g)

### CODE REVIEW

File: app/controllers/api/v1/merchant/items_controller.rb [hunk 1]
```diff
@@ -2,7 +2,7 @@ class Api::V1::Merchant::ItemsController < ApplicationController
   rescue_from ActiveRecord::RecordNotFound, with: :not_found_response
   def index
     raise ActiveRecord::RecordNotFound.new("Merchant not found") unless Merchant.find(params[:id])
-    items = Item.where(merchant_id: params[:id])
+    items = Item.find_by_merchant(params[:id])
```
Comment (Jsphbloom) [inline app/controllers/api/v1/merchant/items_controller.rb:5]: makes sense!

File: app/controllers/api/v1/items_controller.rb
Comment (dontehandy) [inline app/controllers/api/v1/items_controller.rb:1]: The refactoring centralizes parameter validation and item search logic, improving code readability and maintainability. This makes it easier to update and debug the logic in the future.

**Review by Jsphbloom — COMMENTED** [review]
Looks fantastic! Nice work Jaren. Nice to hear the postman tests were broken and it wasn't something else.

File: app/controllers/api/v1/merchants_controller.rb
Comment (dontehandy) [inline app/controllers/api/v1/merchants_controller.rb:1]: The use of dedicated search methods (Merchant.search and Merchant.search_all) improves code readability and maintainability.

File: app/models/item.rb
Comment (dontehandy) [inline app/models/item.rb:1]: new search methods (search and search_all) enhance the flexibility and functionality of item searches, allowing users to filter items by name and price range

**Review by dontehandy — APPROVED** [review]
